- name: create nextcloud network
  docker_network:
    name: "{{ nextcloud_net_name }}"

- name: create nextcloud html volume
  docker_volume:
   name: nextcloud_html

- name: create nextcloud db container
  docker_container:
   name: "{{ nextcloud_db_container_name }}"
   image: "{{ nextcloud_db_image }}:{{ nextcloud_db_image_tag }}"
   pull: false
   restart_policy: no
   state: present
   user: "{{ docker_uid }}:{{ docker_gid }}"
   networks:
    - name: "{{ nextcloud_net_name }}"
   volumes:
    - "{{ nextcloud_db_dir }}:/var/lib/mysql/"
   env:
    MYSQL_ROOT_PASSWORD: "{{ nextcloud_db_root_pwd }}"
    MYSQL_DATABASE: "{{ nextcloud_db_name }}"
    MYSQL_USER: "{{ nextcloud_db_usr }}"
    MYSQL_PASSWORD: "{{ nextcloud_db_pwd }}"
  register: db_result

- name: create nextcloud container
  docker_container:
   name: "{{ nextcloud_container_name }}"
   image: "{{ nextcloud_image }}:{{ nextcloud_image_tag }}"
   pull: false
   restart_policy: no
   state: present
   hostname: nextcloud
   networks:
    - name: "{{ nextcloud_net_name }}"
    - name: "{{ traefik_network_name }}"
   volumes:
    - "nextcloud_html:/var/www/html/"
    - "{{ nextcloud_app_dir }}/config/:/var/www/html/config/"
    - "{{ nextcloud_app_dir }}/custom_apps/:/var/www/html/custom_apps/"
    - "{{ nextcloud_app_dir }}/data/:/var/www/html/data/"
    - "{{ nextcloud_app_dir }}/themes/:/var/www/html/themes/"
   env:
    MYSQL_HOST: "{{ nextcloud_db_container_name }}"
    MYSQL_DATABASE: "{{ nextcloud_db_name }}"
    MYSQL_USER: "{{ nextcloud_db_usr }}"
    MYSQL_PASSWORD: "{{ nextcloud_db_pwd }}"
    NEXTCLOUD_ADMIN_USER: "{{ auth_username }}"
    NEXTCLOUD_ADMIN_PASSWORD: "{{ auth_password }}"
    NEXTCLOUD_DATA_DIR: "/var/www/html/data"
   labels:
    traefik.enable=true
    traefik.docker.network="{{ traefik_network_name }}"
    traefik.backend=nextcloud
    traefik.port=80
    traefik.frontend.rule=Host:cloud."{{ traefik_domain }}" 
  register: app_result

- include_role:
   name: docker_container_service
  vars:
   container_name: "{{ svc.container_name }}"
   template_name: "{{ svc.template_name }}"
   restart_required: "{{ svc.restart_required }}"
  with_items:
   - { container_name: "{{ nextcloud_db_container_name }}", template_name: db.conf.j2, restart_required: "{{ db_result.changed }}" }
   - { container_name: "{{ nextcloud_container_name }}", template_name: app.conf.j2, restart_required: "{{ app_result.changed }}" }
  loop_control:
   loop_var: svc