- name: check if git repo exists
  stat:
   path: "/tmp/{{ delimeat_git_dir }}"
  register: delimeat_repo_dir

- name: clone git repo
  docker_container:
   name: git_temp
   image: "{{ delimeat_git_image }}:{{ delimeat_git_image_tag }}"
   pull: false
   state: started
   command: "clone {{ delimeat_repo }} /tmp/{{ delimeat_git_dir }}"
   detach: no
   interactive: yes
   tty: yes
   recreate: yes
   cleanup: yes
   volumes:
    - "/tmp:/tmp"
  when: not delimeat_repo_dir.stat.exists

- name: build delimeat image
  docker_image:
   path: "/tmp/{{ delimeat_git_dir }}"
   name: "{{ delimeat_image }}"

- name: create delimeat container
  docker_container:
   name: "{{ delimeat_container_name }}"
   image: "{{ delimeat_image }}:{{ delimeat_image_tag }}"
   pull: false
   restart_policy: unless-stopped
   state: started
   network_mode: "container:{{ vpn_client_container_name }}"
   volumes:
    - "{{ delimeat_data_dir }}:/data"
    - "{{ transmission_watch_dir }}:/output"
  notify:
   - restart vpn client