- name: copy service template
  template: 
   src: transmission.service.j2 
   dest: "/etc/systemd/system/transmission.service"
   mode: 0755
  notify:
   - restart transmission

- name: create transmission container
  docker_container:
   name: "{{ transmission_container_name }}"
   image: "{{ transmission_image }}:{{ transmission_image_tag }}"
   pull: false
   restart_policy: no
   state: present
   network_mode: "container:{{ vpn_client_container_name }}"
   volumes:
    - "{{ transmission_config_dir }}:/config"
    - "{{ transmission_downloads_dir }}:/downloads"
    - "{{ transmission_watch_dir }}:/watch"
   env:
    PUID: "{{ docker_uid }}"
    PGID: "{{ docker_gid }}"
    TZ: "{{ docker_tz }}"
   labels:
    traefik.enable=true
    traefik.docker.network="{{ traefik_network_name }}"
    traefik.backend=transmission
    traefik.port=9091
    traefik.frontend.rule=Host:torrent."{{ traefik_domain }}" 
  notify:
   - restart transmission

- name: start transmission
  systemd:
   name: transmission
   state: started
   enabled: yes
   daemon_reload: yes