- name: copy service template
  template: 
   src: transmission-docker.service.j2 
   dest: "/etc/systemd/system/transmission-docker.service"
   mode: 0755
  notify:
   - restart transmission

- name: create transmission container
  docker_container:
   name: "{{ transmission_container_name }}"
   image: "{{ transmission_image }}:{{ transmission_image_tag }}"
   pull: false
   restart_policy: no
   state: present
   network_mode: "container:{{ vpn_client_container_name }}"
   volumes:
    - "{{ transmission_config_dir }}:/config"
    - "{{ transmission_downloads_dir }}:/downloads"
    - "{{ transmission_watch_dir }}:/watch"
   env:
    PGID: "{{ transmission_gid }}"
    PUID: "{{ transmission_uid }}"
    TZ: "{{ linuxserver_tz }}"
  notify:
   - restart transmission

- name: start transmission
  systemd:
   name: transmission-docker
   state: started
   enabled: yes
   daemon_reload: yes