- name: create transmission container
  docker_container:
   name: "{{ transmission_container_name }}"
   image: "{{ transmission_image }}:{{ transmission_image_tag }}"
   pull: false
   restart_policy: no
   state: present
   network_mode: "container:{{ vpn_client_container_name }}"
   volumes:
    - "{{ transmission_config_dir }}:/config"
    - "{{ transmission_downloads_dir }}:/downloads"
    - "{{ transmission_watch_dir }}:/watch"
   env:
    PUID: "{{ docker_uid }}"
    PGID: "{{ docker_gid }}"
    TZ: "{{ docker_tz }}"
   labels:
    traefik.enable=true
    traefik.docker.network="{{ traefik_network_name }}"
    traefik.backend=transmission
    traefik.port=9091
    traefik.frontend.rule=Host:torrent."{{ traefik_domain }}" 
  notify:
   - restart transmission


- include_role:
   name: docker_container_service
  vars:
   container_name: "{{ svc.container_name }}"
   template_name: "{{ svc.template_name }}"
  with_items:
   - { container_name: "{{ transmission_container_name }}", template_name: systemd.conf.j2 }
  loop_control:
   loop_var: svc