- name: install prerequisites
  apt:
   name: "{{ item }}"
   state: present
   update_cache: yes
   install_recommends: no
  with_items: "{{ ddclient_prerequisites }}"

- name: download ddclient 
  get_url:
   url: "{{ ddlclient_url }}"
   dest: /usr/bin/ddclient
   mode: 0755
   owner: root
   group: root

- name: create directories
  file:
   path: "{{ item }}"
   state: directory
   mode: 0755
   owner: root
   group: root
  with_items:
   - /etc/ddclient
   - /var/cache/ddclient

- name: Copy ddclient.conf to /etc/ddclient
  template: 
   src: ddclient.conf.j2 
   dest: /etc/ddclient/ddclient.conf
   mode: 0600
   owner: root
   group: root

- name: create cron tasks for ddclient
  cron:
    name: "run ddclient"
    job: ddclient --force >> /var/log/ddclient.log 2>&1
    minute: "*/5"
    hour: "*"
    day: "*"
    month: "*"
    weekday: "*"