- name: start docker
  systemd:
   name: docker
   state: started

- name: create proxy network
  docker_network:
    name: proxy_net

- name: create guacamole network
  docker_network:
    name: guac_net

- name: create portainer data volume	
  docker_volume:
   name: guacdb_data

- name: create guacamole db directory	
  file:
   path: /opt/docker/guac_db
   state: directory
   mode: 0755

- name: copy initdb.sql to host
  copy:
   src: initdb.sql
   dest: /opt/docker/guac_db/initdb.sql
   mode: 0644

- name: create guac_db container
  docker_container:
   name: guac_db
   image: "mariadb:latest"
   pull: false
   restart_policy: unless-stopped
   state: started
   networks:
    - name: guac_net
   volumes:
    - /opt/docker/guac_db/initdb.sql:/docker-entrypoint-initdb.d/initdb.sql:ro
    - guacdb_data:/var/lib/mysql
   env:
    MYSQL_ROOT_PASSWORD: guac
    MYSQL_DATABASE: guac
    MYSQL_USER: guac
    MYSQL_PASSWORD: guac

- name: create guacd container
  docker_container:
   name: guacd
   image: "guacamole/guacd:latest"
   pull: false
   restart_policy: unless-stopped
   state: started
   networks:
    - name: guac_net

- name: create guacamole container
  docker_container:
   name: guacamole
   image: "guacamole/guacamole:latest"
   pull: false
   restart_policy: unless-stopped
   state: started
   ports:
    - 8080:8080
   networks:
    - name: guac_net
    - name: proxy_net
   env:
    MYSQL_HOSTNAME: guac_db
    MYSQL_DATABASE: guac
    MYSQL_USER: guac
    MYSQL_PASSWORD: guac
    GUACD_HOSTNAME: guacd