- name: copy systemd service file
  copy:
   src: "{{ item }}"
   dest: "/etc/systemd/system/{{ item }}"
   mode: 0755
  with_items:
   - container@.service

- name: "create systemd conf directory for {{ container_name }}"
  file:
   path: "/etc/systemd/system/container@{{ container_name }}.service.d/"
   state: directory
   mode: 0755
  when: template_name is defined

- name: "copy systemd conf template for {{ container_name }}"
  template: 
   src: "{{ template_name }}" 
   dest: "/etc/systemd/system/container@{{ container_name }}.service.d/10-container.conf"
   mode: 0755
  register: results
  when: template_name is defined

- name: "restart service for {{ container_name }}"
  systemd:
   name: "container@{{ container_name }}"
   state: restarted
   enabled: yes
   daemon_reload: yes
  when: results is defined and results.changed

- name: "start service for {{ container_name }}"
  systemd:
   name: "container@{{ container_name }}"
   state: started
   enabled: yes
   daemon_reload: yes
  when: results is not defined or not results.changed


































