- name: install prerequisites
  apt:
   name: "{{ item }}"
   state: present
   update_cache: yes
   install_recommends: no
  with_items: "{{ vpn_client_prerequisites }}"

- name: create directories
  file:
   path: "{{ item }}"
   state: directory
   mode: 0755
  with_items:
   - "{{ vpn_client_dir }}"

- name: copy auth template
  template: 
   src: auth.j2 
   dest: "{{ vpn_client_dir }}/auth"
   mode: 0600
  notify:
   - restart vpn client

- name: copy files
  copy:
   src: "{{ item }}"
   dest: "{{ vpn_client_dir }}/{{ item }}"
   mode: 0755
  with_items:
   - ca.crt
   - ta.key
   - vpn.conf
  notify:
   - restart vpn client

- name: copy service template
  template: 
   src: vpn-client.service.j2 
   dest: "/etc/systemd/system/vpn-client.service"
   mode: 0755
  notify:
   - restart vpn client

- name: create container
  docker_container:
   name: "{{ vpn_client_container_name }}"
   image: "{{ vpn_client_image }}:{{ vpn_client_image_tag }}"
   command: -f ""
   pull: false
   restart_policy: no
   state: present
   networks:
    - name: "{{ traefik_network_name }}"
   volumes:
    - "{{ vpn_client_dir }}:/vpn"
   capabilities:
    - NET_ADMIN
   devices:
    - /dev/net/tun:/dev/net/tun
  notify:
   - restart vpn client

- name: create cron task
  cron:
    name: "restart vpn client"
    job: /bin/systemctl restart vpn-client
    minute: "0"
    hour: "0"
    day: "*"
    month: "*"

- name: start vpn client
  systemd:
   name: vpn-client
   state: started
   enabled: yes
   daemon_reload: yes