- name: install prerequisites
  apt:
   name: "{{ item }}"
   state: present
   update_cache: yes
   install_recommends: no
  with_items: "{{ vpn_client_prerequisites }}"

- name: create directories
  file:
   path: "{{ item }}"
   state: directory
   mode: 0755
  with_items:
   - "{{ vpn_client_dir }}"

- name: copy auth template
  template: 
   src: auth.j2 
   dest: "{{ vpn_client_dir }}/auth"
   mode: 0600
  register: auth_result

- name: copy files
  copy:
   src: "{{ item }}"
   dest: "{{ vpn_client_dir }}/{{ item }}"
   mode: 0755
  with_items:
   - ca.crt
   - ta.key
   - vpn.conf
  register: files_result

- name: create container
  docker_container:
   name: "{{ vpn_client_container_name }}"
   image: "{{ vpn_client_image }}:{{ vpn_client_image_tag }}"
   command: -f ""
   pull: false
   restart_policy: no
   state: present
   networks:
    - name: "{{ traefik_network_name }}"
   volumes:
    - "{{ vpn_client_dir }}:/vpn"
   capabilities:
    - NET_ADMIN
   devices:
    - /dev/net/tun:/dev/net/tun
  register: container_result

- name: create systemd service
  include_role:
   name: docker_container_service
  vars:
   container_name: "{{ vpn_client_container_name }}"
   restart_required: "{{ container_result.changed or files_result.changed or auth_result.changed }}"

- name: create cron task
  cron:
    name: "restart vpn client"
    job: "/bin/systemctl restart container@{{ vpn_client_container_name }}"
    minute: "0"
    hour: "0"
    day: "*"
    month: "*"