- name: copy service template
  template: 
   src: vpn-client-docker.service.j2 
   dest: "/etc/systemd/system/vpn-client-docker.service"
   mode: 0755
  notify:
   - restart vpn client

- name: create vpn client container
  docker_container:
   name: "{{ vpn_client_container_name }}"
   image: "{{ vpn_client_image }}:{{ vpn_client_image_tag }}"
   command: -f ""
   pull: false
   restart_policy: no
   state: present
   networks:
    - name: "{{ proxy_net_name }}"
      ipv4_address: "{{ proxy_net_vpn_client_ip }}"
   volumes:
    - "{{ vpn_client_dir }}:/vpn"
   capabilities:
    - NET_ADMIN
   devices:
    - /dev/net/tun:/dev/net/tun
  notify:
   - restart vpn client

- name: start vpn client
  systemd:
   name: vpn-client-docker
   state: started
   enabled: yes
   daemon_reload: yes