- name: create container
  docker_container:
   name: "{{ jackett_container_name }}"
   image: "{{ jackett_image }}:{{ jackett_image_tag }}"
   pull: false
   restart_policy: no
   state: present
   network_mode: "container:{{ vpn_client_container_name }}"
   volumes:
    - "{{ jackett_config_dir }}:/config"
    - "{{ transmission_watch_dir }}:/downloads"
   env:
    PUID: "{{ docker_uid }}"
    PGID: "{{ docker_gid }}"
    TZ: "{{ docker_tz }}"
   labels:
    traefik.enable=true
    traefik.docker.network="{{ traefik_network_name }}"
    traefik.backend=jackett
    traefik.port=9117
    traefik.frontend.rule=Host:jackett."{{ traefik_domain }}"
  notify:
   - restart jackett

- include_role:
   name: docker_container_service
  vars:
   container_name: "{{ svc.container_name }}"
   template_name: "{{ svc.template_name }}"
  with_items:
   - { container_name: "{{ jackett_container_name }}", template_name: systemd.conf.j2 }
  loop_control:
   loop_var: svc