- name: copy service template
  template: 
   src: jackett.service.j2 
   dest: "/etc/systemd/system/jackett.service"
   mode: 0755
  notify:
   - restart jackett

- name: create container
  docker_container:
   name: "{{ jackett_container_name }}"
   image: "{{ jackett_image }}:{{ jackett_image_tag }}"
   pull: false
   restart_policy: no
   state: present
   network_mode: "container:{{ vpn_client_container_name }}"
   volumes:
    - "{{ jackett_config_dir }}:/config"
    - "{{ transmission_watch_dir }}:/downloads"
   env:
    PUID: "{{ docker_uid }}"
    PGID: "{{ docker_gid }}"
    TZ: "{{ docker_tz }}"
   labels:
    traefik.enable=true
    traefik.docker.network="{{ traefik_network_name }}"
    traefik.backend=jackett
    traefik.port=9117
    traefik.frontend.rule=Host:jackett."{{ traefik_domain }}"
  notify:
   - restart jackett

- name: start jackett
  systemd:
   name: jackett
   state: started
   enabled: yes
   daemon_reload: yes