ssh_port: 22
firewall_policies:
 - { chain: INPUT, jump: DROP }
 - { chain: FORWARD, jump: DROP }
 - { chain: OUTPUT, jump: ACCEPT }
firewall_rules:
 - { chain: INPUT, proto: tcp, match: tcp, dport: "{{ ssh_port }}", cstate: NEW, jump: ACCEPT }
