- name: install transmission-daemon
  apt:
   name: "{{ item }}" 
   state: present
  notify: 
   - restart transmission-daemon
  with_items:
   - transmission-daemon
   - nfs-common
   - acl
- name: open port 9091 for transmission
  ufw:
   rule: 'allow'
   port: '9091'
   proto: 'tcp'
  notify:
   - reload ufw
- name: create {{ transmission_systemd_dir }} directory 
  file:
   path: "{{ transmission_systemd_dir }}"
   state: directory
   owner: root
   group: root
  notify:
   - restart transmission-daemon
- name: add systemd config file for transmission-daemon
  template:
   src: "{{ transmission_systemd_conf }}.j2"
   dest: "{{ transmission_systemd_dir }}/{{ transmission_systemd_conf }}"
   owner: root
   group: root
   mode: 0644
  notify:
   - restart transmission-daemon
- name: create {{ transmission_output_dir }}  directory
  file:
   path: "{{ transmission_output_dir }}"
   state: directory
   owner: root 
   group: root
  notify:
- name: configure /etc/fstab for {{ transmission_output_dir }}
  mount:
   name: "{{ transmission_output_dir }}"
   src: "{{ transmission_nfs_server }}:{{ transmission_nfs_path }}"
   fstype: nfs
   opts: "{{ transmission_nfs_opts }}"
   state: mounted
- name: set file access control for {{ transmission_watch_dir }}
  acl:
   path: "{{ transmission_watch_dir }}"
   default: yes
   etype: user
   entity: debian-transmission
   permissions: rwx
   state: present
  notify:
   - restart transmission-daemon
