- name: check if initdb.sql exists
  stat:
   path: "{{ guac_dir }}/initdb.sql"
  register: guac_initdb_file

- name: extract sql from guacamole container
  docker_container:
   name: guac_temp
   image: "{{ guac_image }}:{{ guac_image_tag }}"
   pull: false
   state: started
   command: "/bin/sh -c '/opt/guacamole/bin/initdb.sh --mysql > /tmp/initdb.sql'"
   detach: no
   interactive: yes
   tty: yes
   recreate: yes
   cleanup: yes
   volumes:
    - "{{ guac_dir }}:/tmp"
  when: not guac_initdb_file.stat.exists

- name: create guacamole network
  docker_network:
    name: guac_net

- name: create guac_db container
  docker_container:
   name: "{{ guac_db_container_name }}"
   image: "{{ guac_db_image }}:{{ guac_db_image_tag }}"
   pull: false
   restart_policy: no
   state: present
   user: "{{ docker_uid }}:{{ docker_gid }}"
   networks:
    - name: guac_net
   volumes:
    - "{{ guac_dir }}/initdb.sql:/docker-entrypoint-initdb.d/initdb.sql:ro"
    - "{{ guac_db_dir }}:/var/lib/mysql"
   env:
    MYSQL_ROOT_PASSWORD: "{{ guac_db_root_pwd }}"
    MYSQL_DATABASE: "{{ guac_db_name }}"
    MYSQL_USER: "{{ guac_db_usr }}"
    MYSQL_PASSWORD: "{{ guac_db_pwd }}"
  register: db_result

- name: create guacd container
  docker_container:
   name: "{{ guacd_container_name }}"
   image: "{{ guacd_image }}:{{ guacd_image_tag }}"
   pull: false
   restart_policy: no
   state: present
   networks:
    - name: guac_net
  register: daemon_result

- name: create guacamole container
  docker_container:
   name: "{{ guac_container_name }}"
   image: "{{ guac_image }}:{{ guac_image_tag }}"
   pull: false
   restart_policy: no
   state: present
   networks:
    - name: guac_net
    - name: "{{ traefik_network_name }}"
   env:
    MYSQL_HOSTNAME: "{{ guac_db_container_name }}"
    MYSQL_DATABASE: "{{ guac_db_name }}"
    MYSQL_USER: "{{ guac_db_usr }}"
    MYSQL_PASSWORD: "{{ guac_db_pwd }}"
    GUACD_HOSTNAME: "{{ guacd_container_name }}"
   labels:
    traefik.enable=true
    traefik.docker.network="{{ traefik_network_name }}"
    traefik.backend=guac
    traefik.port=8080
    traefik.frontend.rule=Host:guac."{{ traefik_domain }};AddPrefix:/guacamole" 
  register: app_result

- include_role:
   name: docker_container_service
  vars:
   container_name: "{{ svc.container_name }}"
   template_name: "{{ svc.template_name }}"
   restart_required: "{{ svc.restart_required }}"
  with_items:
   - { container_name: "{{ guac_db_container_name }}", template_name: db.conf.j2, restart_required: "{{ db_result.changed }}" }
   - { container_name: "{{ guacd_container_name }}", template_name: daemon.conf.j2, restart_required: "{{ daemon_result.changed }}" }
   - { container_name: "{{ guac_container_name }}", template_name: app.conf.j2, restart_required: "{{ app_result.changed }}" }
  loop_control:
   loop_var: svc