- name: install ufw packages
  apt:
   name: "{{ item }}"
   state: present
  with_items: "{{ ufw_prerequisites }}"

- name: disable ipv6 in ufw
  lineinfile:
   name: /etc/default/ufw
   regexp: '^IPV6='
   line: 'IPV6=no'
  notify:
   - reload ufw

- name: configure ufw defaults 
  ufw:
   policy: "{{ item.policy }}"
   direction: "{{ item.direction }}"
  with_items: "{{ ufw_default_rules }}"
  notify:
   - reload ufw

- name: configure ufw rules
  ufw:
   rule: "{{ item.rule }}"
   port: "{{ item.port }}"
   proto: "{{ item.proto }}"
  with_items: "{{ ufw_rules }}"
  notify:
   - reload ufw

- name: start ufw
  ufw:
   state: enabled