- name: create portainer container
  docker_container:
   name: "{{ portainer_container_name }}"
   image: "{{ portainer_image }}:{{ portainer_image_tag }}"
   command: "--no-auth"
   pull: false
   restart_policy: unless-stopped
   state: started
   networks:
    - name: "{{ proxy_net_name }}"
      ipv4_address: "{{ proxy_net_portainer_ip }}"
   volumes:
    - "/var/run/docker.sock:/var/run/docker.sock"
    - "{{ portainer_dir }}:/data"