- name: create volume
  docker_volume:
   name: "{{ portainer_volume_name }}" 
   state: present

- name: create container
  docker_container:
   name: "{{ portainer_container_name }}"
   image: "{{ portainer_image }}:{{ portainer_image_tag }}"
   hostname: portainer
   command: "--no-auth"
   pull: false
   restart_policy: unless-stopped 
   state: started
   networks:
    - name: "{{ traefik_network_name }}"
   volumes:
    - "/var/run/docker.sock:/var/run/docker.sock"
    - "{{ portainer_volume_name }}:/data"
   labels:
    traefik.enable=true
    traefik.docker.network="{{ traefik_network_name }}"
    traefik.backend=portainer
    traefik.port=9000
    traefik.frontend.rule=Host:portainer."{{ traefik_domain }}" 