- name: restart guacamole db
  systemd:
   name: guacamole-db
   state: restarted
   daemon_reload: yes

- name: restart guacd
  systemd:
   name: guacd
   state: restarted
   daemon_reload: yes

- name: restart guacamole app
  systemd:
   name: guacamole
   state: restarted
   daemon_reload: yes