- name: copy service template
  template: 
   src: radarr-docker.service.j2 
   dest: "/etc/systemd/system/radarr-docker.service"
   mode: 0755
  register:
   copy_template
  notify:
   - restart radarr

- name: reload systemd daemon
  systemd:
   name: radarr-docker
   daemon_reload: yes
  when:
   copy_template.changed

- name: create radarr container
  docker_container:
   name: "{{ radarr_container_name }}"
   image: "{{ radarr_image }}:{{ radarr_image_tag }}"
   pull: false
   restart_policy: no
   state: present
   network_mode: "container:{{ vpn_client_container_name }}"
   volumes:
    - "{{ radarr_config_dir }}:/config"
    - "{{ transmission_downloads_dir }}:/downloads"
    - "{{ radarr_movies_dir }}:/movies"
    - /etc/localtime:/etc/localtime:ro
   env:
    PGID: "{{ radarr_gid }}"
    PUID: "{{ radarr_uid }}"
    TZ: "{{ linuxserver_tz }}"
  notify:
   - restart radarr

- name: start radarr
  systemd:
   name: radarr-docker
   state: started
   enabled: yes