- name: create container
  docker_container:
   name: "{{ radarr_container_name }}"
   image: "{{ radarr_image }}:{{ radarr_image_tag }}"
   pull: false
   restart_policy: no
   state: present
   network_mode: "container:{{ vpn_client_container_name }}"
   volumes:
    - "{{ radarr_config_dir }}:/config"
    - "{{ transmission_downloads_dir }}:/downloads"
    - "{{ radarr_movies_dir }}:/movies"
   env:
    PUID: "{{ docker_uid }}"
    PGID: "{{ docker_gid }}"
    TZ: "{{ docker_tz }}"
   labels:
    traefik.enable=true
    traefik.docker.network="{{ traefik_network_name }}"
    traefik.backend=radarr
    traefik.port=7878
    traefik.frontend.rule=Host:radarr."{{ traefik_domain }}" 
  register: result

- include_role:
   name: docker_container_service
  vars:
   container_name: "{{ radarr_container_name }}"
   template_name: systemd.conf.j2
   restart_required: "{{ result.changed }}"