- name: copy service template
  template: 
   src: plex-docker.service.j2 
   dest: "/etc/systemd/system/plex-docker.service"
   mode: 0755
  register:
   copy_template
  notify:
   - restart plex

- name: reload systemd daemon
  systemd:
   name: plex-docker
   daemon_reload: yes
  when:
   copy_template.changed

- name: create plex container
  docker_container:
   name: "{{ plex_container_name }}"
   image: "{{ plex_image }}:{{ plex_image_tag }}"
   pull: false
   restart_policy: no
   state: present
   hostname: "{{ plex_hostname }}"
   networks:
    - name: "{{ proxy_net_name }}"
      ipv4_address: "{{ proxy_net_plex_ip }}"
   ports:
    - "{{ plex_http_port }}:32400/tcp"
    - 3005:3005/tcp
    - 8324:8324/tcp
    - 32469:32469/tcp
    - 1900:1900/udp
    - 32410:32410/udp
    - 32412:32412/udp
    - 32413:32413/udp
    - 32414:32414/udp
   env:
    ADVERTISE_IP: "http://{{ ansible_default_ipv4.address }}:{{ plex_http_port }}"
    HOSTNAME: "{{ plex_hostname }}"
   volumes:
    - "{{ plex_config_dir }}:/config"
    - "{{ plex_data_dir }}:/data"
    - "{{ plex_transcode_dir }}:/transcode"
  notify:
   - restart plex

- name: start plex
  systemd:
   name: plex-docker
   state: started
   enabled: yes