- name: create container
  docker_container:
   name: "{{ sonarr_container_name }}"
   image: "{{ sonarr_image }}:{{ sonarr_image_tag }}"
   pull: false
   restart_policy: no
   state: present
   network_mode: "container:{{ vpn_client_container_name }}"
   volumes:
    - "{{ sonarr_config_dir }}:/config"
    - "{{ transmission_downloads_dir }}:/downloads"
    - "{{ sonarr_tv_dir }}:/tv"
   env:
    PUID: "{{ docker_uid }}"
    PGID: "{{ docker_gid }}"
    TZ: "{{ docker_tz }}"
   labels:
    traefik.enable=true
    traefik.docker.network="{{ traefik_network_name }}"
    traefik.backend=sonarr
    traefik.port=8989
    traefik.frontend.rule=Host:sonarr."{{ traefik_domain }}" 
  register: result

- include_role:
   name: docker_container_service
  vars:
   container_name: "{{ sonarr_container_name }}"
   template_name: systemd.conf.j2
   restart_required: "{{ result.changed }}"