- name: copy service template
  template: 
   src: sonarr-docker.service.j2 
   dest: "/etc/systemd/system/sonarr-docker.service"
   mode: 0755
  notify:
   - restart sonarr

- name: create sonarr container
  docker_container:
   name: "{{ sonarr_container_name }}"
   image: "{{ sonarr_image }}:{{ sonarr_image_tag }}"
   pull: false
   restart_policy: no
   state: present
   network_mode: "container:{{ vpn_client_container_name }}"
   volumes:
    - "{{ sonarr_config_dir }}:/config"
    - "{{ transmission_downloads_dir }}:/downloads"
    - "{{ sonarr_tv_dir }}:/tv"
   env:
    PGID: "{{ sonarr_gid }}"
    PUID: "{{ sonarr_uid }}"
    TZ: "{{ linuxserver_tz }}"
  notify:
   - restart sonarr

- name: start sonarr
  systemd:
   name: sonarr-docker
   state: started
   enabled: yes
   daemon_reload: yes