- name: install docker prerequisites
  apt:
   name: "{{ item }}"
   state: present
   update_cache: yes
   install_recommends: no
  with_items: 
   - apt-transport-https
   - ca-certificates
   - software-properties-common
   - python-pip
- name: add docker apt key
  apt_key:
   keyserver: hkp://p80.pool.sks-keyservers.net:80
   state: present
   id: 58118E89F3A912897C070ADBF76221572C52609D
- name: add docker repo 
  apt_repository:
   repo: deb https://apt.dockerproject.org/repo {{ ansible_distribution | lower }}-{{ ansible_distribution_release | lower }} main
   state: present
- name: install docker 
  apt:
   name: "{{ item }}"
   state: present
   update_cache: yes
   install_recommends: no
  with_items: 
   - docker-engine
  notify:
   - restart docker
- name: install docker-py
  pip: 
   name: "{{ item }}"
  with_items:
   - setuptools
   - docker-py