- name: install docker prerequisites
  apt:
   name: "{{ item }}"
   state: present
   update_cache: yes
   install_recommends: no
  with_items: 
   - apt-transport-https
   - ca-certificates
   - software-properties-common
   - python-pip
   - python-pkg-resources
   - cron

- name: add docker apt key
  apt_key:
   url: https://download.docker.com/linux/{{ ansible_distribution | lower }}/gpg
   id: 9DC858229FC7DD38854AE2D88D81803C0EBFCD88
   state: present

- name: add docker repo 
  apt_repository:
   repo: deb [arch=amd64] https://download.docker.com/linux/{{ ansible_distribution | lower }} {{ ansible_distribution_release | lower }} edge
   state: present

- name: install docker 
  apt:
   name: "{{ item }}"
   state: present
   update_cache: yes
   install_recommends: no
  with_items: 
   - docker-ce
  notify:
   - restart docker

- name: add users to "docker" group
  user:
    name: "{{ item }}"
    groups: "docker"
    append: yes
  with_items: "{{ docker_users }}"
  when: docker_users

- name: install docker-py
  pip: 
   name: "{{ item }}"
  with_items:
   - setuptools
   - docker-py

- name: create cron tasks for docker
  cron:
    name: "docker clean up"
    job: docker system prune -f
    minute: "0"
    hour: "0"
    day: "*"
    month: "*"
    weekday: "0"
    