- name: install docker prerequisites
  apt:
   name: "{{ item }}"
   state: present
   update_cache: yes
   install_recommends: no
  with_items: "{{ docker_prequisites }}"

- name: install docker-py
  pip:
   name: "{{ item }}"
  with_items: "{{ docker_pip_prequisites }}"

- name: add docker apt key
  apt_key:
   url: "{{ docker_apt_key_url }}"
   id: "{{ docker_apt_key_fingerprint }}"
   state: present

- name: add docker repo 
  apt_repository:
   repo: deb [arch=amd64] {{ docker_apt_url }} {{ ansible_distribution_release | lower }} {{ docker_release_channel }}
   state: present

- name: install docker 
  apt:
   name: "{{ item }}"
   state: present
   update_cache: yes
   install_recommends: no
  with_items: 
   - "{{ docker_version }}"

- name: add users to "docker" group
  user:
    name: "{{ item }}"
    groups: "docker"
    append: yes
  with_items: "{{ docker_users }}"
  when: docker_users

- name: create cron tasks for docker
  cron:
    name: "docker clean up"
    job: docker system prune -f
    minute: "0"
    hour: "0"
    day: "*"
    month: "*"
    weekday: "0"

- name: start docker service
  systemd:
   name: docker
   state: started    