- name: install docker prerequisites
  yum:
   name: "{{ item }}"
   state: present
   update_cache: yes
  with_items: 
   - yum-utils
- name: Add docker repository
  yum_repository:
    name: docker
    description: docker repo
    baseurl: https://docs.docker.com/engine/installation/linux/repo_files/{{ ansible_distribution | lower }}/docker.repo
- name: install docker
  yum:
   name: "{{ item }}"
   state: present
   update_cache: yes
  with_items: 
   - docker-engine
  notify:
   - restart docker 
