- name: check if git repo exists
  stat:
   path: "/tmp/{{ ffmpeg_git_dir }}"
  register: ffmpeg_repo_dir

- name: clone git repo
  docker_container:
   name: git_temp
   image: "{{ ffmpeg_git_image }}:{{ ffmpeg_git_image_tag }}"
   pull: false
   state: started
   command: "clone {{ ffmpeg_repo }} /tmp/{{ ffmpeg_git_dir }}"
   detach: no
   interactive: yes
   tty: yes
   recreate: yes
   cleanup: yes
   volumes:
    - "/tmp:/tmp"
  when: not ffmpeg_repo_dir.stat.exists

- name: build ffmpeg image
  docker_image:
   path: "/tmp/{{ ffmpeg_git_dir }}"
   name: "{{ ffmpeg_image }}"

- name: create ffmpeg container
  docker_container:
   name: "{{ ffmpeg_container_name }}"
   image: "{{ ffmpeg_image }}:{{ ffmpeg_image_tag }}"
   pull: false
   restart_policy: no
   state: present
   volumes:
    - "{{ transmission_downloads_dir }}/complete:/watch"
    - "{{ ffmpeg_process_dir }}:/process"
    - "{{ ffmpeg_error_dir }}:/error"
    - "{{ ffmpeg_archive_dir }}:/archive"
    - "{{ ffmpeg_output_dir }}:/output"